version: "3"

services: #Define os serviços que compõem a aplicação
  app:
    build: . # O "." indica que a imagem do docker será construída a partir do diretório atual, ou na raíz do package.json
    # Os 2 comandos a serem executados quando o serviço app iniciar
    command: /bin/sh -c "npm install && npm start"
    ports: # Mapeia a porta 5000 do container para a porta 5000 da máquina
      - "5000:5000"
    volumes: # Monta o diretório atual da máquina dentro do diretório usr/app dentro do container
      - .:/usr/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always # Configura o container para reiniciar automaticamente caso pare
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports: # Mapeia a porta 3306 do container para a porta 3306 da máquina
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
    db_data: #Define um volume nomeado db_data para persistir os dados do banco de dados
